### ISSUE TITLE
"Add your Application" documentation is not working

### ISSUE THREAD

**Issue by Mtze** [eclipsesource/theia-cloud-website#29]
The documentation to configure custom Theia images here:  

```
content/documentation/addApplication/content.md
```

is not working unfortunately. 

I think it should be mentioned that it is a requirement to clone the theia-blueprint repo first to be able to build the docker image. 

Still, even if the Dockerfile outlined on the page is built within the repo, the process fails with 

```
457.8 $ theia-patch
457.8 /bin/sh: 1: theia-patch: not found
457.8 error Command failed with exit code 127.
``` 

I guess it would be good to update the page with a working example Docker file.

**Comment by jfaltermeier** [comment]
Thank you for the report, there was a breaking change in Theia 1.48, so we probably need this change here as well: https://github.com/eclipse-theia/theia-blueprint/commit/e840a8a2dff2510adadd40e022b3ed7b8cf77885
